### ISSUE TITLE
Initialize Database

### ISSUE THREAD

**Issue by len06** [HomeworkTracker/homework-tracker-backend#6]
__Acceptance_Criteria__:
- Initialize Database 
- Make Entity-Relation Model

**Comment by 0xEbrahim** [comment]
maybe more details for this?

**Comment by joserigel** [comment]
> maybe more details for this?

Currently assigned to me

**Comment by 0xEbrahim** [comment]
ok, thx

**Comment by joserigel** [comment]
Project Initialized
